Repository pestras-uo/pestras, pull requests merged in 2023-11, with the labels that each got.

#88 bug fixes
  apps/api/src/validators/active-directory.ts
  apps/platform/src/app/main/blueprints/views/collaborators/collaborators.view.ts
  apps/platform/src/app/main/topics/views/topics-list/topics-list.view.ts
  apps/platform/src/app/main/users/modals/add-user/add-user.modal.ts
  apps/platform/src/app/main/users/modals/update-roles/update-roles.modal.ts
  apps/platform/src/app/main/users/views/user-details/user-details.view.ts
  libs/frontend/features/entity-access/src/lib/entity-access/entity-access.view.html
  libs/frontend/state/src/lib/topics/topics.state.ts
  libs/frontend/state/src/lib/workspaces/workspace.state.ts
  libs/frontend/util/stator/src/lib/group.ts
  libs/shared/data-model/src/lib/active-directory/role.ts
Labels: bug Fix

#95 add partners feature
  apps/api/src/api/orgunits/validators.ts
  apps/platform/src/app/app.routes.ts
  apps/platform/src/app/main/orgunits/modals/create-orgunit/create-orgunit.modal.html
  apps/platform/src/app/main/orgunits/modals/create-orgunit/create-orgunit.modal.ts
  apps/platform/src/app/main/orgunits/modals/update-orgunit-logo/update-orgunit-logo.modal.html
  apps/platform/src/app/main/orgunits/modals/update-orgunit/update-orgunit.modal.html
  apps/platform/src/app/main/orgunits/modals/update-orgunit/update-orgunit.modal.ts
  apps/platform/src/app/main/orgunits/orgunits.page.ts
  apps/platform/src/app/main/orgunits/views/orgunit-details/orgunit-details.view.html
  apps/platform/src/app/main/orgunits/views/orgunit-details/orgunit-details.view.ts
  apps/platform/src/app/main/orgunits/views/orgunits-list/orgunits-list.view.html
  apps/platform/src/app/main/orgunits/views/orgunits-list/orgunits-list.view.ts
  apps/platform/src/app/main/orgunits/views/orgunits-table/orgunits-table.view.html
  apps/platform/src/app/main/orgunits/views/orgunits-table/orgunits-table.view.ts
  apps/platform/src/app/main/regions/views/region-details/region-details.view.html
  apps/platform/src/app/main/regions/views/regions-list/regions-list.view.html
  apps/platform/src/app/main/users-groups/views/list/list.view.html
  apps/platform/src/app/main/users/views/users-list/users-list.view.html
  apps/platform/src/app/main/views/drawer/drawer.view.html
  apps/platform/src/app/main/views/drawer/drawer.view.ts
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  apps/platform/src/assets/svg/partners.svg
  libs/backend/models/src/lib/active-directory/orgunits/create.ts
  libs/shared/data-model/src/lib/active-directory/orgunit/api.ts
  libs/shared/data-model/src/lib/active-directory/orgunit/index.ts
Labels: feature

#97 Heatmap chart
  apps/api/src/api/users/index.ts
  apps/api/src/validators/data-viz.ts
  apps/platform/src/app/main/dashboards/details/details.page.ts
  apps/platform/src/app/main/data-stores/modals/add-relation-chart/add-relation-chart.modal.component.html
  apps/platform/src/app/main/records/views/sub-data-stores-records/sub-data-stores-records.view.html
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  libs/frontend/features/data-viz/src/index.ts
  libs/frontend/features/data-viz/src/lib/data-viz.module.ts
  libs/frontend/features/data-viz/src/lib/forms/chart/chart.form.html
  libs/frontend/features/data-viz/src/lib/forms/chart/chart.form.ts
  libs/frontend/features/data-viz/src/lib/forms/heatmap-chart/heatmap-chart.form.html
  libs/frontend/features/data-viz/src/lib/forms/heatmap-chart/heatmap-chart.form.ts
  libs/frontend/features/data-viz/src/lib/views/chart/chart.view.html
  libs/frontend/features/data-viz/src/lib/views/heatmap-chart/heatmap-chart.view.ts
  libs/shared/data-model/src/lib/dashboard.ts
  libs/shared/data-model/src/lib/statistics/data-viz/aggregate/group.ts
  libs/shared/data-model/src/lib/statistics/data-viz/bar.ts
  libs/shared/data-model/src/lib/statistics/data-viz/heatmap.ts
  libs/shared/data-model/src/lib/statistics/data-viz/index.ts
  libs/shared/data-model/src/lib/statistics/data-viz/types.ts
Labels: feature

#99 improve regions page
  apps/platform/src/app/main/regions/views/region-details/region-details.view.html
  apps/platform/src/app/main/regions/views/region-details/region-details.view.scss
  apps/platform/src/app/main/regions/views/region-details/region-details.view.ts
  apps/platform/src/app/main/regions/views/regions-list/regions-list.view.html
  apps/platform/src/app/main/regions/views/regions-list/regions-list.view.ts
Labels: UI/UX

#100 Support in memory api
  apps/api/src/api/data-stores/validators.ts
  apps/platform/src/app/main/data-stores/views/table-settings/form-model.ts
  apps/platform/src/app/main/data-stores/views/table-settings/table-settings.view.html
  apps/platform/src/app/main/data-stores/views/table-settings/table-settings.view.ts
  apps/platform/src/app/main/data-stores/views/web-service-settings/general/form.model.ts
  apps/platform/src/app/main/data-stores/views/web-service-settings/general/general.view.html
  apps/platform/src/app/main/data-stores/views/web-service-settings/general/general.view.ts
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  apps/ws-import-job/src/generate-payload.ts
  apps/ws-import-job/src/handle-request.ts
  apps/ws-import-job/src/handle-response.ts
  apps/ws-import-job/src/job.ts
  libs/backend/models/src/lib/blueprints/data-stores/create.ts
  libs/backend/models/src/lib/blueprints/data-stores/web-service.ts
  libs/backend/models/src/lib/blueprints/records/read.ts
  libs/backend/util/src/index.ts
  libs/backend/util/src/lib/web-service/generate-payload.ts
  libs/backend/util/src/lib/web-service/generate-request.ts
  libs/backend/util/src/lib/web-service/generate-response.ts
  libs/backend/util/src/lib/web-service/index.ts
  libs/backend/util/src/lib/web-service/types.ts
  libs/shared/data-model/src/lib/blueprint/data-store.ts
  libs/shared/data-model/src/lib/blueprint/web-service/index.ts
  libs/shared/data-model/src/lib/blueprint/web-service/intervals.ts
  libs/shared/data-model/src/lib/util/aggr-pipline/stages/merge.ts
  libs/shared/data-model/src/lib/util/index.ts
Labels: feature

#101 Integrate with gis
  apps/api/src/api/orgunits/controller.ts
  apps/api/src/api/region/controller.ts
  apps/api/src/api/region/index.ts
  apps/api/src/api/region/types.ts
  apps/api/src/api/region/validators.ts
  apps/platform/src/app/app.component.ts
  apps/platform/src/app/main/records/views/sub-data-stores-records/sub-data-stores-records.view.html
  apps/platform/src/app/main/records/views/sub-data-stores-records/sub-data-stores-records.view.ts
  apps/platform/src/app/main/regions/modals/add-gis-layer/add-gis-layer.modal.component.html
  apps/platform/src/app/main/regions/modals/add-gis-layer/add-gis-layer.modal.component.ts
  apps/platform/src/app/main/regions/modals/add-gis-map/add-gis-map.modal.component.html
  apps/platform/src/app/main/regions/modals/add-gis-map/add-gis-map.modal.component.ts
  apps/platform/src/app/main/regions/modals/update-gis-map/update-gis-map.modal.component.html
  apps/platform/src/app/main/regions/modals/update-gis-map/update-gis-map.modal.component.ts
  apps/platform/src/app/main/regions/modals/update-map-layer/update-map-layer.modal.component.html
  apps/platform/src/app/main/regions/modals/update-map-layer/update-map-layer.modal.component.ts
  apps/platform/src/app/main/regions/regions.module.ts
  apps/platform/src/app/main/regions/views/gis-view/gis-view.component.html
  apps/platform/src/app/main/regions/views/gis-view/gis-view.component.ts
  apps/platform/src/app/main/regions/views/region-details/region-details.view.html
  apps/platform/src/app/main/regions/views/region-details/region-details.view.scss
  apps/platform/src/app/main/regions/views/region-details/region-details.view.ts
  apps/platform/src/app/main/regions/views/regions-list/regions-list.view.html
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  apps/platform/src/assets/svg/add_layer.svg
  apps/platform/src/index.html
  apps/platform/src/styles.scss
  libs/backend/models/src/index.ts
  libs/backend/models/src/lib/active-directory/regions/create.ts
  libs/backend/models/src/lib/active-directory/regions/gis.ts
  libs/backend/models/src/lib/active-directory/regions/index.ts
  libs/backend/models/src/lib/active-directory/regions/update.ts
  libs/frontend/features/dashboards/src/lib/views/dashboard-slide/dashboard-slide.view.html
  libs/frontend/features/dashboards/src/lib/views/dashboard-slide/dashboard-slide.view.ts
  libs/frontend/state/src/lib/regions/regions.api.ts
  libs/frontend/state/src/lib/regions/regions.service.ts
  libs/frontend/state/src/lib/regions/regions.state.ts
  libs/frontend/ui/src/assets/reset.scss
  libs/frontend/ui/src/assets/variables.scss
  libs/frontend/ui/src/index.ts
  libs/frontend/ui/src/lib/gis-map/gis-map.component.ts
  libs/frontend/ui/src/lib/gis-map/gis-map.module.ts
  libs/frontend/ui/src/lib/gis-map/types.ts
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.component.html
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.component.ts
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.module.ts
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.service.ts
  libs/shared/data-model/src/lib/active-directory/orgunit/api.ts
  libs/shared/data-model/src/lib/active-directory/region/api.ts
  libs/shared/data-model/src/lib/active-directory/region/index.ts
  libs/shared/util/src/lib/serial.ts
  package-lock.json
  package.json
Labels: feature

#104 Fix: #103 finish control-font-size
  apps/platform/src/app/main/main.module.ts
  apps/platform/src/app/main/views/main-header/main-header.view.html
  apps/platform/src/app/main/views/main-header/main-header.view.scss
  apps/platform/src/app/main/views/main-header/main-header.view.ts
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  apps/platform/src/assets/svg/minus.svg
  apps/platform/src/assets/svg/paint.svg
  apps/platform/src/assets/svg/text_decrease.svg
  apps/platform/src/assets/svg/text_increase.svg
  libs/frontend/ui/src/assets/reset.scss
  libs/frontend/ui/src/assets/util/font.scss
  libs/frontend/ui/src/index.ts
  libs/frontend/ui/src/lib/font-size/font-size.component.ts
  libs/frontend/ui/src/lib/font-size/font-size.module.ts
  libs/frontend/ui/src/lib/font-size/font-size.service.ts
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.component.html
  libs/frontend/ui/src/lib/toggle-theme/toggle-theme.component.ts
Labels: UI/UX
