Repository pestras-uo/pestras, pull requests merged in 2023-09, with the labels that each got.

#25 fix select input options overlapping
  libs/frontend/ui/src/lib/multi-select-input/multi-select-input.component.html
  libs/frontend/ui/src/lib/select-input/select-input.component.html
Labels: bug Fix

#26 improve avatar widget
  apps/platform/src/app/main/main.page.ts
  apps/platform/src/app/main/views/drawer/drawer.view.html
  apps/platform/src/app/main/views/drawer/drawer.view.scss
  apps/platform/src/app/main/views/drawer/drawer.view.ts
  libs/frontend/ui/src/assets/util/misc.scss
  libs/frontend/widgets/avatar/src/lib/avatar.widget.html
  libs/frontend/widgets/avatar/src/lib/avatar.widget.ts
Labels: UI/UX

#30 Feature record history
  apps/api/src/api/data-stores/records/controller.ts
  apps/api/src/api/data-stores/records/index.ts
  apps/api/src/api/data-stores/records/types.ts
  apps/platform/src/app/main/records/add-form/add-form.page.ts
  apps/platform/src/app/main/records/details/details.page.html
  apps/platform/src/app/main/records/details/details.page.ts
  apps/platform/src/app/main/records/records-routing.module.ts
  apps/platform/src/app/main/records/records.module.ts
  apps/platform/src/app/main/records/update-form/update-form.page.ts
  apps/platform/src/app/main/records/views/desc/desc.view.html
  apps/platform/src/app/main/records/views/desc/desc.view.ts
  apps/platform/src/app/main/records/views/history/history.view.html
  apps/platform/src/app/main/records/views/history/history.view.ts
  apps/platform/src/app/main/records/views/side-menu/side-menu.view.html
  apps/platform/src/app/main/records/views/side-menu/side-menu.view.ts
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  libs/backend/models/src/lib/blueprints/records/history.ts
  libs/backend/models/src/lib/blueprints/records/index.ts
  libs/backend/models/src/lib/blueprints/records/update.ts
  libs/backend/models/src/lib/blueprints/records/util.ts
  libs/frontend/features/data-records/src/lib/pipes/query-records.pipe.ts
  libs/frontend/features/data-records/src/lib/pipes/record.pipe.ts
  libs/frontend/features/data-records/src/lib/pipes/records.pipe.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-cards/records-cards.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-list.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-table/records-table.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-tree/records-tree.view.ts
  libs/frontend/features/data-stores/src/lib/pipes/field-value.pipe.ts
  libs/frontend/features/data-stores/src/lib/pipes/select-record.pipe.ts
  libs/frontend/features/data-viz/src/lib/views/chart/chart.view.ts
  libs/frontend/state/src/index.ts
  libs/frontend/state/src/lib/records/record.resolver.ts
  libs/frontend/state/src/lib/records/records-entities.state.ts
  libs/frontend/state/src/lib/records/records.api.ts
  libs/frontend/state/src/lib/records/records.service.ts
  libs/frontend/state/src/lib/records/records.state.ts
  libs/frontend/state/src/lib/state.module.ts
  libs/frontend/ui/src/assets/components/list.scss
  libs/frontend/ui/src/assets/util/font.scss
  libs/frontend/util/stator/src/lib/query.ts
  libs/shared/data-model/src/lib/blueprint/records.ts
Labels: feature

#32 Apply stator query state
  apps/api/src/api/categories/controller.ts
  apps/api/src/api/categories/index.ts
  apps/api/src/api/categories/types.ts
  apps/platform/src/app/app.module.ts
  apps/platform/src/app/main/main.module.ts
  apps/platform/src/app/main/main.page.ts
  apps/platform/src/app/main/views/drawer/drawer.view.html
  apps/platform/src/app/main/views/drawer/drawer.view.ts
  libs/backend/models/src/lib/blueprints/categories/index.ts
  libs/backend/models/src/lib/blueprints/categories/read.ts
  libs/frontend/features/categories/src/lib/pipes/bp-categories.pipe.ts
  libs/frontend/features/categories/src/lib/pipes/category-branches.pipe.ts
  libs/frontend/features/categories/src/lib/views/categories-list/categories-list.view.html
  libs/frontend/features/categories/src/lib/views/category-details/category-details.view.html
  libs/frontend/features/data-stores/src/lib/forms/field-input/field-input.form.html
  libs/frontend/features/data-stores/src/lib/forms/field/field.form.html
  libs/frontend/state/src/index.ts
  libs/frontend/state/src/lib/activities/activities.state.ts
  libs/frontend/state/src/lib/attachments/attachments.service.ts
  libs/frontend/state/src/lib/attachments/attachments.state.ts
  libs/frontend/state/src/lib/blueprints/blueprints.service.ts
  libs/frontend/state/src/lib/categories/categories.api.ts
  libs/frontend/state/src/lib/categories/categories.service.ts
  libs/frontend/state/src/lib/categories/categories.state.ts
  libs/frontend/state/src/lib/client-api/client-api.listeners.ts
  libs/frontend/state/src/lib/client-api/client-api.service.ts
  libs/frontend/state/src/lib/client-api/client-api.state.ts
  libs/frontend/state/src/lib/content/content.service.ts
  libs/frontend/state/src/lib/content/content.state.ts
  libs/frontend/state/src/lib/dashboards/dashboards.service.ts
  libs/frontend/state/src/lib/dashboards/dashboards.state.ts
  libs/frontend/state/src/lib/data-stores/data-stores.listeners.ts
  libs/frontend/state/src/lib/data-stores/data-stores.service.ts
  libs/frontend/state/src/lib/data-stores/data-stores.state.ts
  libs/frontend/state/src/lib/data_viz/data-viz.service.ts
  libs/frontend/state/src/lib/data_viz/data-viz.state.ts
  libs/frontend/state/src/lib/orgunits/orgunits.service.ts
  libs/frontend/state/src/lib/records/records.service.ts
  libs/frontend/state/src/lib/records/records.state.ts
  libs/frontend/state/src/lib/regions/regions.service.ts
  libs/frontend/state/src/lib/reports/reports.service.ts
  libs/frontend/state/src/lib/reports/reports.state.ts
  libs/frontend/state/src/lib/session/session.service.ts
  libs/frontend/state/src/lib/state.module.ts
  libs/frontend/state/src/lib/topics/topics.listeners.ts
  libs/frontend/state/src/lib/topics/topics.service.ts
  libs/frontend/state/src/lib/topics/topics.state.ts
  libs/frontend/state/src/lib/users-groups/users-groups.service.ts
  libs/frontend/state/src/lib/users/users.state.ts
  libs/frontend/state/src/lib/workflow/workflow.service.ts
  libs/frontend/state/src/lib/workflow/workflow.state.ts
  libs/frontend/state/src/lib/workspaces/workspace.service.ts
  libs/frontend/ui/src/index.ts
  libs/frontend/ui/src/lib/click-outside/click-outside.directive.ts
  libs/frontend/ui/src/lib/util-pipes/config.ts
  libs/frontend/ui/src/lib/util-pipes/docs-path.pipe.ts
  libs/frontend/util/stator/src/lib/query.ts
  libs/frontend/util/stator/src/lib/types.ts
Labels: optimization

#34 create notifications state
  libs/frontend/state/src/index.ts
  libs/frontend/state/src/lib/notifications/notifications.api.ts
  libs/frontend/state/src/lib/notifications/notifications.service.ts
  libs/frontend/state/src/lib/notifications/notifications.state.ts
  libs/frontend/state/src/lib/state.module.ts
Labels: feature

#36 Select columns on tables
  apps/platform/src/app/main/dashboards/main/main.page.ts
  apps/platform/src/app/main/topics/details/details.page.html
  apps/platform/src/app/main/topics/views/data-stores-records/data-stores-records.view.ts
  apps/platform/src/app/main/views/main-header/main-header.view.html
  apps/platform/src/assets/content/ar.json
  apps/platform/src/assets/content/en.json
  apps/platform/src/assets/svg/columns.svg
  apps/platform/src/assets/svg/more.svg
  libs/frontend/features/data-records/src/lib/pipes/query-records.pipe.ts
  libs/frontend/features/data-records/src/lib/pipes/records.pipe.ts
  libs/frontend/features/data-records/src/lib/records.module.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-cards/records-cards.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-list.view.html
  libs/frontend/features/data-records/src/lib/views/records-list/records-list.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-table/records-table.view.html
  libs/frontend/features/data-records/src/lib/views/records-list/records-table/records-table.view.ts
  libs/frontend/features/data-records/src/lib/views/records-list/records-tree/records-tree.view.ts
  libs/frontend/features/data-stores/src/lib/pipes/select-record.pipe.ts
  libs/frontend/features/data-viz/src/lib/views/chart/chart.view.ts
  libs/frontend/state/src/lib/activities/activities.state.ts
  libs/frontend/state/src/lib/attachments/attachments.state.ts
  libs/frontend/state/src/lib/categories/categories.state.ts
  libs/frontend/state/src/lib/client-api/client-api.state.ts
  libs/frontend/state/src/lib/content/content.state.ts
  libs/frontend/state/src/lib/dashboards/dashboards.api.ts
  libs/frontend/state/src/lib/dashboards/dashboards.state.ts
  libs/frontend/state/src/lib/data-stores/data-stores.state.ts
  libs/frontend/state/src/lib/data_viz/data-viz.state.ts
  libs/frontend/state/src/lib/records/records.api.ts
  libs/frontend/state/src/lib/records/records.state.ts
  libs/frontend/state/src/lib/reports/reports.state.ts
  libs/frontend/state/src/lib/state.module.ts
  libs/frontend/state/src/lib/topics/topics.state.ts
  libs/frontend/state/src/lib/workflow/workflow.state.ts
  libs/frontend/ui/src/assets/components/list.scss
  libs/frontend/ui/src/lib/dropdown/dropdown.component.ts
  libs/frontend/util/stator/src/index.ts
  libs/frontend/util/stator/src/lib/group.ts
  libs/frontend/util/stator/src/lib/query.ts
  libs/frontend/util/stator/src/lib/types.ts
Labels: utility

#38 fix record field upload
  apps/api/src/api/data-stores/records/controller.ts
  apps/api/src/api/data-stores/records/types.ts
  apps/api/src/api/data-stores/records/validators.ts
  apps/platform/src/app/main/records/update-form/update-form.page.ts
  libs/backend/models/src/lib/blueprints/records/update.ts
  libs/frontend/state/src/lib/records/records.api.ts
  libs/frontend/state/src/lib/records/records.service.ts
  libs/frontend/state/src/lib/records/records.state.ts
Labels: bug Fix

#39 fix data-viz search
  apps/platform/src/app/main/dashboards/main/main.page.html
  apps/platform/src/app/main/dashboards/main/main.page.ts
  libs/frontend/state/src/lib/content/content.state.ts
  libs/frontend/state/src/lib/records/records.state.ts
Labels: bug Fix

#40 clients api server
  .eslintrc.json
  apps/clients-api/.eslintrc.json
  apps/clients-api/jest.config.ts
  apps/clients-api/project.json
  apps/clients-api/src/assets/.gitkeep
  apps/clients-api/src/config.ts
  apps/clients-api/src/error.ts
  apps/clients-api/src/get-ip-address.ts
  apps/clients-api/src/main.ts
  apps/clients-api/src/models.ts
  apps/clients-api/src/req-handler.ts
  apps/clients-api/tsconfig.app.json
  apps/clients-api/tsconfig.json
  apps/clients-api/tsconfig.spec.json
  apps/ws-import-job/src/job.ts
  apps/ws-import-job/src/models.ts
  libs/backend/models/src/index.ts
  libs/backend/models/src/lib/blueprints/clients-api-log/index.ts
  libs/backend/models/src/lib/blueprints/clients-api/index.ts
  libs/backend/models/src/lib/blueprints/data-stores/index.ts
  libs/backend/models/src/lib/blueprints/records/index.ts
  libs/backend/models/src/lib/blueprints/web-service-error-log/index.ts
  libs/backend/models/src/lib/blueprints/web-service-log/index.ts
  libs/shared/data-model/src/lib/blueprint/client_api.ts
  libs/shared/data-model/src/lib/blueprint/web-service/log.ts
  package-lock.json
  package.json
Labels: feature

#41 Export reports to pdf utility
  apps/platform/src/app/app.module.ts
  apps/platform/src/app/main/reports/reports.module.ts
  apps/platform/src/styles.scss
  libs/frontend/features/reports/src/lib/reports.module.ts
  libs/frontend/features/reports/src/lib/views/report-slide/report-slide.view.html
  libs/frontend/features/reports/src/lib/views/report-slide/report-slide.view.ts
  libs/frontend/ui/src/assets/util/font.scss
  libs/frontend/ui/src/index.ts
  libs/frontend/ui/src/lib/export-pdf/export-to-pdf.directive.ts
  package-lock.json
  package.json
Labels: utility

#42 optimize export to pdf directive
  apps/platform/src/app/app.module.ts
  apps/platform/src/app/main/reports/reports.module.ts
  libs/frontend/features/data-viz/src/lib/views/bar-chart/bar-chart.view.ts
  libs/frontend/features/reports/src/lib/reports.module.ts
  libs/frontend/features/reports/src/lib/views/report-slide/report-slide.view.html
  libs/frontend/features/reports/src/lib/views/report-slide/report-slide.view.ts
  libs/frontend/ui/src/lib/export-pdf/export-to-pdf.directive.ts
  package-lock.json
  package.json
Labels: optimization

#45 move region model to AD
  apps/api/src/models.ts
  libs/shared/data-model/src/index.ts
  libs/shared/data-model/src/lib/active-directory/index.ts
  libs/shared/data-model/src/lib/active-directory/region.ts
Labels: optimization

#48 fix attachments uploads
  apps/api/src/models.ts
  libs/frontend/ui/src/lib/file-input/file-input.component.ts
  libs/frontend/ui/src/lib/image-input/image-input.component.ts
Labels: bug Fix
